I totally messed up something but I think re-writing in_int is the only way forward

diff --git a/compiler/run-test b/compiler/run-test
--- a/compiler/run-test
+++ b/compiler/run-test
@@ -5,10 +5,10 @@ if [ "$#" -gt 1 ]; then
     input=$2
 fi
 
-echo "Input: $input"
-
 cool_output=$(echo $input | cool "$1.cl")
+cool_output2=$(cat "test_input" | cool "$1.cl")
 dune_output=$(echo $input | ./run-full "$1")
+dune_output2=$(cat "test_input" | ./a.out)
 
 if [ "$cool_output" != "$dune_output" ]; then
     echo "Test failed: $1"
@@ -19,8 +19,14 @@ if [ "$cool_output" != "$dune_output" ]; then
     exit 1
 fi
 
-echo "Expected output: $cool_output"
-echo "Got: $dune_output"
+if [ "$cool_output2" != "$dune_output2" ]; then
+    echo "Test failed: $1"
+    echo "Expected: $cool_output2"
+    echo "Got: $dune_output2"
+    rm "$1".cl-type
+    rm "$1".s
+    exit 1
+fi
 
 rm "$1".cl-type
 rm "$1".s
